# ghacHook config file

[Devices]
# Simulates an I/O board.
# Set this to "true" if your I/O board is broken or missing.
EnableIOHooks=false
# Prevent the security dongle from being read from/written to.
# THE DONGLE IS STILL REQUIRED TO BOOT THE GAME.
# Set this to "true" if you are not in a real arcade setting.
EnableDongleHooks=false

[Filesystem]
# Redirects saves, config files, and game file contents to be loaded from the
#  same folder as GH3.exe.
# Set this to "true" if you have multiple GHAC/GH3 installs on the same box.
EnableMultiInstallHook=false
# Skips over doing file CRC32 checksums. Makes the game load much faster,
#  however if the drive or game files are corrupted the game will crash with
#  no warning.
# Set this to "true" if you are not in a real arcade setting.
SkipCRCChecks=false

[IO]
# Changes the flipped state of the dip switches if "EnableIOHooks" is true.
# Dip switch 1 is leftmost, dip switch 8 is rightmost. For example, to turn on
#  both Family Mode options, this would be "11000000".
DipSwitch=00000110
